name: Gatsby Publisher

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        git config --global user.name 'jraleman'
        git config --global user.email 'jraleman@bendiburg.com'
    - run: yarn install
    - run: yarn deploy
