name: Gatsby Publisher

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: OleksiyRudenko/gha-git-credentials@v2
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn deploy
